# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    ignore:
      # Fails plugin bill of materials tests
      # https://github.com/jenkinsci/bom/issues/3171
      - dependency-name: "org.jenkins-ci.plugins:promoted-builds"
    labels:
      - "dependencies"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "skip-changelog"
    schedule:
      interval: "monthly"
